### ISSUE TITLE
[Wrath Classic] Errors due to missing function

### ISSUE THREAD

**Issue by Road-block** [fubaWoW/fuba_CinematicSkip#1]
To have this work in Wrath Classic I had to add a shim for `MovieFrame_StopMovie` which does not exist on that client (probably same for 1.15)

```lua
local MovieFrame_StopMovie = MovieFrame_StopMovie or function(frame)
  if MovieFrame_OnMovieFinished then
    MovieFrame_OnMovieFinished(MovieFrame)
  else
    GameMovieFinished()
    MovieFrameSubtitleString:Hide()
    MovieFrame:StopMovie()
    WorldFrame:Show()
    if ( MovieFrame.uiParentShown ) then
      UIParent:Show()
      SetUIVisibility(true)
    end
  end
end
```
towards the top of the file lets the addon work on both clients.

**Comment by Road-block** [comment]
This is relevant for previous but also current (at time of posting) `100205.02-Release`

**Comment by fubaWoW** [comment]
oh ok, i've not tested it on classic wor wrath at all tbh 🤣
and now i have no active auscription...
But...
i will add it later, thanks!
